classdef Scene
    properties (Dependent)
        robotPosition
    end
    properties
        sim
        clientID
        rightMotor
        leftMotor
        pioneerP3DX
        inertialFrame
    end
    methods

        function obj = Scene(sim, clientID)
            obj.sim = sim;
            obj.clientID = clientID;
            obj.rightMotor = obj.getElement('Pioneer_p3dx_rightMotor');
            obj.leftMotor = obj.getElement('Pioneer_p3dx_leftMotor');
            obj.pioneerP3DX = obj.getElement('Pioneer_p3dx');
            obj.inertialFrame = obj.getElement('Floor');

            obj.setRobotVelocity(obj.rightMotor, 0);
            obj.setRobotVelocity(obj.leftMotor, 0);
        end

        function element = getElement(obj, elementString)
            [~, element] = obj.sim.simxGetObjectHandle( ...
                obj.clientID, ...
                elementString, ...
                obj.sim.simx_opmode_oneshot_wait ...
            );
        end

        function position = get.robotPosition(obj)
            for i = 1:5
                [~, position] = obj.sim.simxGetObjectPosition( ...
                    obj.clientID, ...
                    obj.pioneerP3DX, ...
                    obj.inertialFrame, ...
                    obj.sim.simx_opmode_oneshot_wait ...
                );
                [~, orientation] = obj.sim.simxGetObjectOrientation( ...
                    obj.clientID, ...
                    obj.pioneerP3DX, ...
                    obj.inertialFrame, ...
                    obj.sim.simx_opmode_oneshot_wait ...
                );
            end
            position(3) = adjustAngle(orientation(3));
        end

        function setRobotVelocity(obj, element, velocity)
            obj.sim.simxSetJointTargetVelocity( ...
                obj.clientID, ...
                element, ...
                velocity, ...
                obj.sim.simx_opmode_oneshot ...
            );
        end

        function addStatusBarMessage(obj, message)
            obj.sim.simxAddStatusbarMessage( ...
                obj.clientID, ...
                message, ...
                obj.sim.simx_opmode_oneshot ...
            );
        end

    end
end